const MODAL_CONSTANTS = {
  SHOW_ACCOUNT_MODAL: 'SHOW_ACCOUNT_MODAL',
  HIDE_ACCOUNT_MODAL: 'HIDE_ACCOUNT_MODAL',
  SHOW_WETH_MODAL: 'SHOW_WETH_MODAL',
  HIDE_WETH_MODAL: 'HIDE_WETH_MODAL',
  SHOW_CONNECT_WALLET_MODAL: 'SHOW_CONNECT_WALLET_MODAL',
  HIDE_CONNECT_WALLET_MODAL: 'HIDE_CONNECT_WALLET_MODAL',
}

export default MODAL_CONSTANTS
